// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChM8lKBIHYXv6FhqgHGB3qBnwY6GZGRm8',
    appId: '1:161381533203:web:9b3c506d30cbda2014a1e6',
    messagingSenderId: '161381533203',
    projectId: 'emart-28023',
    authDomain: 'emart-28023.firebaseapp.com',
    storageBucket: 'emart-28023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6fJ31Oc3Diol3xxJDa9-9u74CuXJs36s',
    appId: '1:161381533203:android:8dbff43d7b0669b814a1e6',
    messagingSenderId: '161381533203',
    projectId: 'emart-28023',
    storageBucket: 'emart-28023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_2efPFqGWWb4UDi49OB1SDU3mJRtTZ5g',
    appId: '1:161381533203:ios:efde4cc495a9bd8414a1e6',
    messagingSenderId: '161381533203',
    projectId: 'emart-28023',
    storageBucket: 'emart-28023.appspot.com',
    iosClientId: '161381533203-etdnsqdc0vg7m9gigv05i1k1ekuq1lsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.emart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_2efPFqGWWb4UDi49OB1SDU3mJRtTZ5g',
    appId: '1:161381533203:ios:77c19839044f9a0214a1e6',
    messagingSenderId: '161381533203',
    projectId: 'emart-28023',
    storageBucket: 'emart-28023.appspot.com',
    iosClientId: '161381533203-a082gqsv4qgvqdon3tsv8ci8k89hk630.apps.googleusercontent.com',
    iosBundleId: 'com.example.emart.RunnerTests',
  );
}
